const fetch = require("node-fetch");

test("Receive a new message", async () => {
  expect.assertions(2);

  const request = await fetch(`http://localhost:5000/mail`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      email: "test@florian-hansen.com",
      message: "This is generated by a test case. Just ignore this.",
    }),
  });

  const response = await request.json();

  expect(response.status).toBe(200);
  expect(response.message).not.toBeUndefined();
});
